<?php if (!defined ('ABSPATH')) die ('Not allowed'); ?><div class="wrap">
	
	<h2><?php printf (__ ("Resources", 'faqtastic'), htmlspecialchars ($group->name)); ?></h2>
	<?php $this->submenu (true); ?>
	<h2><?php _e ('FAQ-Tastic Video Tutorials', 'faqtastic'); ?></h2>
	<p style="clear: both"></p>
	
	<div id="mediaPlayer">
		<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="690" height="380" id="xspfPlayer" class="xspfJukeboxPlayer">
			<param name="movie" value="http://faq-tastic.com/media/xspf/xspf_jukebox.swf" />
			<param name="quality" value="best" />

			<param name="wmode" value="opaque" />
			<param name="allowfullscreen" value="false" />
			<param name="allowscriptaccess" value="always" />
			<param name="flashvars" value="loadurl=http://faq-tastic.com/media/xspf/kc-flv-player_lite/variables.txt&amp;skin_url=http://faq-tastic.com/media/xspf/kc-flv-player_lite/" />
			<!--[if !IE]>-->
			<object type="application/x-shockwave-flash" data="http://faq-tastic.com/media/xspf/xspf_jukebox.swf" width="690" height="380" class="xspfJukeboxPlayer">
				<param name="quality" value="best" />
				<param name="wmode" value="opaque" />
				<param name="allowfullscreen" value="false" />

				<param name="allowscriptaccess" value="always" />
				<param name="flashvars" value="loadurl=http://faq-tastic.com/media/xspf/kc-flv-player_lite/variables.txt&amp;skin_url=http://faq-tastic.com/media/xspf/kc-flv-player_lite/" />
			<!--<![endif]-->
				<a href="http://www.adobe.com/go/getflashplayer">
					<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
				</a>
			<!--[if !IE]>-->
			</object>
			<!--<![endif]-->

		</object>
	</div>

	<h2><?php _e ('Additional Resources', 'faqtastic'); ?></h2>
	<p><?php _e ('The following resources may contain affiliate links. The revenue generated by some of these programs help toward maintaining and updating of the FAQ-Tastic plugin and hosting costs.', 'faqtastic'); ?></p>
	<script type="text/javascript" src="http://faq-tastic.com/media/js/resources.js" /></script>
	
	<h2 align="center"><?php _e ('Problems Viewing This Page?', 'faqtastic'); ?></h2>
	<p>
	<?php _e ('<b>Note:</b> If you cannot see the video or the text for the additional resources, then you may have an Ad Blocker preventing you from seeing this page properly.', 'faqtastic'); ?><br>
	<?php _e ('This page gets data from from the main "faq-tastic.com" website. Ensure you whitelist the FAQ-Tastic.com site in your Ad Blocker to view additional content.', 'faqtastic'); ?>
	</p>
</div>